proyecto/Apps/Almacen/urls.py
from django.conf.urls import url
from proyecto.Apps.Almacen.views import index
from proyecto.Apps.Almacen.views import almacen_view, almacen_list, almacen_edit, almacen_delete, \
	AlmacenList,AlmacenCreate,AlmacenUpdate, AlmacenDelete



urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', AlmacenCreate.as_view(), name='almacen_crear'),
    url(r'^listar$', AlmacenList.as_view(), name='almacen_listar'),
    url(r'^editar/(?P<pk>\d+)/$', AlmacenUpdate.as_view(), name='almacen_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$',AlmacenDelete.as_view() , name='almacen_eliminar'),






]

proyecto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^almacen/', include('proyecto.Apps.Almacen.urls', namespace="almacenIndex")),
    url(r'^venta/', include('proyecto.Apps.Venta.urls', namespace="ventaIndex")),
    url(r'^usuario/', include('proyecto.Apps.Usuario.urls', namespace="usuarioIndex")),
    url(r'^$', login,{'template_name':'index.html'}, name="login"),
    url(r'^reset/password_reset', password_reset,
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),

]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
    <head>
        {% block extrahead %}
        {% endblock %}

        <meta charset="UTF-8">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
        <title>{% block title %} Document {% endblock %}</title>
    </head>
    <body>


        {% block navbar %}
            <section class="title">
		<h1>Menu</h1>
	</section>
            <nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-ex1-collapse">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Logotipo</a>
  </div>

  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Almacen <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'almacenIndex:almacen_crear' %}">Ingreso</a></li>
          <li><a href="#">Proveedor</a></li>
          <li><a href="#">Acción #3</a></li>
          <li class="divider"></li>
          <li><a href="#">Acción #4</a></li>
          <li class="divider"></li>
          <li><a href="#">Acción #5</a></li>
        </ul>
      </li>
    </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Admin <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Ingreso</a></li>
          <li><a href="#">Acción #2</a></li>
          <li><a href="#">Acción #3</a></li>
          <li class="divider"></li>
          <li><a href="#">Acción #4</a></li>
          <li class="divider"></li>
          <li><a href="#">Acción #5</a></li>
        </ul>
      </li>
    </ul>




      <ul class="nav navbar-nav">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Venta <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Ingreso</a></li>
          <li><a href="#">Acción #2</a></li>
          <li><a href="#">Acción #3</a></li>
          <li class="divider"></li>
          <li><a href="#">Acción #4</a></li>
          <li class="divider"></li>
          <li><a href="#">Acción #5</a></li>
        </ul>
      </li>
    </ul>


    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Buscar">
      </div>
      <button type="submit" class="btn btn-default">Enviar</button>
    </form>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Enlace #3</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Menú #2 <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Acción #1</a></li>
          <li><a href="#">Acción #2</a></li>
          <li><a href="#">Acción #3</a></li>
          <li class="divider"></li>
          <li><a href="#">Acción #4</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
        {% endblock %}
        {% include 'base/header.html' %}

        {% block content %}
        <h4>Bloque de contenido</h4>
        {% endblock %}


        {% block footer %}
        {% endblock %}
    </div>
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        {% block extrajs %}
        {% endblock %}


    </body>
</html>

templates/base/header.html
<h1></h1>